Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/mtbp3cd-OLnEGR1N-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
(crosstab_from_lists(df, rows, cols, ['A', 'D']), row_margin_perct=True, col_margin_perct=True)['report']
------------------


[0;36m  Cell [0;32mIn[9], line 1[0;36m[0m
[0;31m    (crosstab_from_lists(df, rows, cols, ['A', 'D']), row_margin_perct=True, col_margin_perct=True)['report'][0m
[0m                                                      ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid syntax. Maybe you meant '==' or ':=' instead of '='?


